spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/quizDb}
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://zipkin:9411}
  sleuth:
    zipkin:
      base-url: ${SPRING_ZIPKIN_BASE_URL:http://zipkin:9411}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://service-registry:8761/eureka}
